#ifndef ACTIONS_H
#define ACTIONS_H

enum Action {
    ACTION_NONE,
    ACTION_SPAWN,
    ACTION_CLOSE,
    ACTION_FOCUS_NEXT,
    ACTION_MOVE,
    ACTION_RESIZE,
    ACTION_CYCLE_LAYOUT,
    ACTION_EXIT,
    ACTION_SPACE_1,
    ACTION_SPACE_2,
    ACTION_SPACE_3,
    ACTION_SPACE_4,
    ACTION_SPACE_5,
    ACTION_SPACE_6,
    ACTION_SPACE_7,
    ACTION_SPACE_8,
    ACTION_SPACE_9,
    ACTION_SPACE_10,
    ACTION_MOVE_TO_SPACE_1,
    ACTION_MOVE_TO_SPACE_2,
    ACTION_MOVE_TO_SPACE_3,
    ACTION_MOVE_TO_SPACE_4,
    ACTION_MOVE_TO_SPACE_5,
    ACTION_MOVE_TO_SPACE_6,
    ACTION_MOVE_TO_SPACE_7,
    ACTION_MOVE_TO_SPACE_8,
    ACTION_MOVE_TO_SPACE_9,
    ACTION_MOVE_TO_SPACE_10,
};

#endif // ACTIONS_H
